### ISSUE TITLE
Error during update

### ISSUE THREAD

**Issue by Jose-Rondon** [Toetje585/Age-of-Empires-Online-Lutris#4]
### Hi, I'm trying to update but I get this:

`Extracting
Unhandled exception: System.IO.IOException: No space left on device
   at System.IO.FileStream.WriteNative(ReadOnlySpan`1 source)
   at System.IO.FileStream.WriteSpan(ReadOnlySpan`1 source)
   at System.IO.FileStream.Write(Byte[] array, Int32 offset, Int32 count)
   at System.IO.Stream.<>c.<BeginWriteInternal>b__51_0(Object <p0>)
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location where exception was thrown ---
   at System.IO.Stream.EndWrite(IAsyncResult asyncResult)
   at System.IO.Stream.<>c.<BeginEndWriteAsync>b__61_1(Stream stream, IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncTrimPromise`1.Complete(TInstance thisRef, Func`3 endMethod, IAsyncResult asyncResult, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at ProjectCeleste.GameFiles.Tools.Utils.L33TZipUtils.DecompressL33TZipAsync(Stream inputStream, Stream outputStream, IProgress`1 progress, CancellationToken ct)
   at ProjectCeleste.GameFiles.Tools.Utils.L33TZipUtils.DecompressL33TZipAsync(String fileName, String outputFileName, IProgress`1 progress, CancellationToken ct)
   at ProjectCeleste.GameFiles.GameScanner.GameScannerManager.ScanAndRepairFile(GameFileInfo fileInfo, String gameFilePath, PathTransformer pathTransformer, IProgress`1 progress, Int32 concurrentDownload, CancellationToken ct)
   at ProjectCeleste.GameFiles.GameScanner.GameScannerManager.ScanAndRepair(IProgress`1 progress, IProgress`1 subProgress, Int32 concurrentDownload)
   at ProjectCeleste.GameFiles.GameScanner.GameScannerManager.ScanAndRepair(IProgress`1 progress, IProgress`1 subProgress, Int32 concurrentDownload)
   at Celeste.GameScan.Program.<>c.<<Main>b__0_0>d.MoveNext() in /home/joser/Celeste.GameScan/Program.cs:line 47
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Invocation.CommandHandler.GetResultCodeAsync(Object value, InvocationContext context)
   at System.CommandLine.Invocation.ModelBindingCommandHandler.InvokeAsync(InvocationContext context)
   at System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass4_0.<<BuildInvocationChain>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseParseErrorReporting>b__21_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass16_0.<<UseHelp>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass25_0.<<UseVersionOption>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass23_0.<<UseTypoCorrections>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseSuggestDirective>b__22_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseParseDirective>b__20_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseDebugDirective>b__11_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<RegisterWithDotnetSuggest>b__10_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass14_0.<<UseExceptionHandler>b__0>d.MoveNext()
`

### What should I do? I'm on Manjaro.

**Comment by Toetje585** [comment]
Hello did you notice this:

Extracting Unhandled exception: System.IO.IOException: **No space left on device** at System.IO.FileStream.WriteNative(ReadOnlySpan1 source)

Can you check if you have enough free space?

Also note the gamescan repo is here:

https://github.com/ProjectCeleste/Celeste.GameScan

**Comment by Jose-Rondon** [comment]
Yeah, I saw that but I have plenty of space, should I ask in Celeste.gamescan repo? I didn't that... Well because is a Linux thing and they would probably told me they don't support the platform

**Comment by Toetje585** [comment]
> Yeah, I saw that but I have plenty of space, should I ask in Celeste.gamescan repo? I didn't that... Well because is a Linux thing and they would probably told me they don't support the platform

Hello,

The gamescan was made for linux in mind, however I have strong doubts if this is code related.

Just to be sure lets check the space once more:

run "`df -h`" in terminal and report back

**Comment by Jose-Rondon** [comment]
hi! as I told you before I have a lot of gigs available, I don't know what can be causing the problem but is not space.
Now, I installed all the libraries for 32bit execution but I don't know if I need to active something more for that.

**Comment by Toetje585** [comment]
> hi! as I told you before I have a lot of gigs available, I don't know what can be causing the problem but is not space.
> Now, I installed all the libraries for 32bit execution but I don't know if I need to active something more for that.

Hello,

I just try to be carefull before contacting the developer, if you search on the web for this issue you always see that on the end there is real a space issue. What filesystem is the winprefix drives using?

**Comment by Jose-Rondon** [comment]
32 arch for the bottle

**Comment by Toetje585** [comment]
Hello,

I could not reproduce this issue on Ubuntu 20.04, works fine here. Did you install .NET Core 3.1?

**Comment by Jose-Rondon** [comment]
Yep!, I'll try again to check if I can fix it I guess
